config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

  resources :events, only: [:create, :destroy, :show, :index] do
    member do
      post "join"
      delete "leave"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "events#index"

  get "/event", to: "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past_events, -> { where("date < ?", Time.now) }
  scope :upcoming_events, -> { where("date > ?", Time.now) }
  validates :name, presence: true
  validates :date, presence: true
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :user_events
  has_many :participants, through: :user_events, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :events
  has_many :created_events, class_name: "Event", foreign_key: "user_id", dependent: :destroy
  has_many :user_events
  has_many :participated_events, through: :user_events, source: :event
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # Permit the `name` parameter for Devise sign up and account update
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @events = Event.includes(:creator).all
  end

  def create
    @user = current_user
    @event = @user.created_events.new(event_params)
    if @event.valid?
      @event.save
      redirect_back(fallback_location: request.referer)
    else
      @events = @user.created_events
      @past_events = @user.participated_events.past_events || []
      @upcoming_events = @user.participated_events.upcoming_events || []
      render "users/show", status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:notice] = "The event #{@event.name} has been deleted"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Sorry event cannot be deleted"
      redirect_back
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def join
    @user = current_user
    @event = Event.find(params[:id])
    @join_event = UserEvent.new(user: @user, event: @event)
    if @event.creator == current_user
      flash[:notice] = "You cant join your own event"
    elsif UserEvent.exists?(user_id: current_user.id, event_id: @event.id)
      flash[:notice] = "You have already joined this event"
    elsif @join_event.valid?
      @join_event.save
      flash[:success] = "You have joined event #{@event.name}"
    else
      flash[:alert] = "Unable to join the event"
    end
    redirect_to event_path(@event)
  end

  def leave
    @event = Event.find(params[:id])
    @join_event = UserEvent.find_by(user_id: current_user.id, event_id: @event.id)
    if @join_event&.destroy
      redirect_to event_path(@event)
    else
      flash[:notice] = "Unable to leave this event "
      redirect_to event_path(@event)
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @events = @user.created_events #is passed in users/show.html.erb
    @event = Event.new #is passed in users/show.html.erb to show form error.
    @past_events = @user.participated_events.past_events.includes(:creator)
    @upcoming_events = @user.participated_events.upcoming_events.includes(:creator)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%#! is being rendered from users/show.html.erb  %>
<%= form_with(model: @event, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :name, "Event Name", class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
    <% event.errors.full_messages_for(:name).each do |msg| %>
      <div class="error"><%= msg %></div>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :location, "Event Location", class: "form-label" %>
    <%= f.text_field :location, class: "form-control" %>
    <% event.errors.full_messages_for(:location).each do |msg| %>
      <div class="error"><%= msg %></div>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :date, 'Date', class: "form-label" %>
    <%= f.date_field :date, class: "form-control" %>
    <% event.errors.full_messages_for(:date).each do |msg| %>
      <div class="error"><%= msg %></div>
    <% end %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/events/_show.html.erb
<%#! is rendered in events/show.html.erb event is passed from there aswell  %>
<div class="container">
  <div class="row d-flex justify-content-around">
    <div class="card col-12 col-md-6 mb-3">
      <div class="card-header">
        <h3 class="card-title">Event Details</h3>
      </div>
      <div class="card-body">
        <p><strong>Title:</strong>
          <%= event.name.capitalize %>
          <% if event.creator != current_user %>
            <% if event.date < Time.now %>
              <span class="badge bg-secondary text-light">Finished</span>
            <% else %>
              <% if UserEvent.exists?(user_id: current_user.id, event_id: event.id) %>
                <%= link_to "Attending", event_path(event), data: { turbo_method: :post }, class: "btn btn-sm btn-success" %>
              <% else %>
                <%= link_to "Attend", join_event_path(event), data: { turbo_method: :post }, class: "btn btn-sm btn-primary" %>
              <% end %>
              <%= link_to "Leave", leave_event_path(event), data: { turbo_method: :delete, turbo_confirm: "Are you sure to not attend thisevent?" }, class: "btn btn-sm btn-danger" %>
            <% end %>
          <% end %>
        </p>
        <p><strong>Organizer:</strong> <%= event.creator.name %>
          <% if event.creator == current_user %>
            <span class="badge bg-primary text-light">Your event</span>
          <% end %>
        </p>
        <p><strong>Venue:</strong> <%= event.location %></p>
        <p><strong>Date:</strong> <%= event.date %></p>
      </div>
    </div>
    <div class="card col-12 col-md-6 mb-3">
      <div class="card-header">
        <h3 class="card-title">Participants</h3>
      </div>
      <div class="card-body overflow-auto h-50">
        <ul class="list-group list-group-flush">
          <% event.participants.each do |participant| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <span><b><%= participant.name %></b></span>
              <span class="text-muted"><%= participant.email %></span>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-between mt-3">
    <%= link_to "Your Events", user_path(current_user), class: "btn btn-dark" %>
    <%= link_to "All Events", root_path, class: "btn btn-secondary" %>
    <% if event.creator == current_user %>
      <%= link_to "Delete Event", event_path(event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<h1 class="my-4">List of All Events</h1>
<div class="list-group">
  <% @events.each do |event| %>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%=link_to event.name, event_path(event) %></h5>
        <small>by <%= event.creator.name %></small>
      </div>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<%#! Here we can simply do render "show" and @event will be still available in child view that is _show.html.erb directly from parent that is EventsController show method  %>
<%#todo However by explicitly defining local variables makes other devs understand the code more  %>
<%= render partial: "show", locals: {event:@event}%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Your Events", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <div class="debug">
      <%= debug(params).html_safe %>
    </div>
    <div class="navigation">
      <%= render partial: "layouts/navbar" %>
    </div>
    <div class="alert">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_attended_events.html.erb
<%#! is rendered in events/show.html.erb %>
<%# todo user is received from event/show.html.erb which parent class is EventsController show method %>
<div class="">
  <h1 class="mb-2 text-center display-4">Attended Events</h1>
  <div class="row">
    <% if events.any? %>
      <% events.each do |event| %>
        <div class="col-md-6 mb-4">
          <div class="card h-100">
            <div class="card-header bg-primary text-white">
              <h5 class="mb-1"><%= event.name %></h5>
            </div>
            <div class="card-body d-flex flex-column">
              <p class="mb-1"><strong>Creator:</strong> <%= event.creator.name %></p>
              <p class="mb-1"><strong>Location:</strong> <%= event.location %></p>
              <small class="text-muted mb-2"><strong>Date:</strong> <%= event.date %></small>
              <a href="<%= event_path(event) %>" class="btn btn-outline-primary mt-auto">View Details</a>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center">No upcoming events found.</p>
    <% end %>
  </div>
</div>

app/views/users/_upcoming_events.html.erb
<div class="">
  <h1 class="mb-2 text-center display-4">Upcoming Events</h1>
  <div class="row">
    <% if events.any? %>
      <% events.each do |event| %>
        <div class="col-md-6 mb-4">
          <div class="card h-100">
            <div class="card-header bg-primary text-white">
              <h5 class="mb-1"><%= event.name %></h5>
            </div>
            <div class="card-body d-flex flex-column">
              <p class="mb-1"><strong>Creator:</strong> <%= event.creator.name %></p>
              <p class="mb-1"><strong>Location:</strong> <%= event.location %></p>
              <small class="text-muted mb-2"><strong>Date:</strong> <%= event.date %></small>
              <a href="<%= event_path(event) %>" class="btn btn-outline-primary mt-auto">View Details</a>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center">No upcoming events found.</p>
    <% end %>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h2 class="text-center border p-3 mb-4">All list of events created by this user</h2>
<div class="row">
  <div class="col-md-6">
    <div class="card mb-4">
      <div class="card-header">
        <h3 class="card-title">Your events</h3>
      </div>
      <div class="card-body">
        <%#! @events from UserController show method  %>
        <%#! Also from EventsController create method to render same page once event is created  %>
        <% if @events.any? %>
          <ul class="list-group">
            <% @events.each do |event| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <span><%=event.name %></span>
                <%#!  user_event GET    /users/:user_id/events/:id(.:format) for show therefore need to provide creator & event for this link  %>
                <% if event.persisted? %>
                  <span class="badge badge-primary badge-pill">
                    <%= link_to "Detail", event_path(event), class: "text-light" %>
                  </span>
                <% end %>
                <span class="badge badge-primary badge-pill"><%= event.date %></span>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p class="text-muted">No events found.</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card mb-4">
      <div class="card-header">
        <h3 class="card-title">Create new events</h3>
      </div>
      <div class="card-body">
        <%#! form partial is rendered here  %>
        <%= render partial: "events/form", locals: {event: @event} %>
        <%#todo { event: Event.new, user: current_user } at first i did this but the errors message was not showing in form becuase everytime i submit form it created new instace of Event therefore it did not show error. Therefore in order to show error i have to put the same instance @event which i passed from UsersController show method%>
      </div>
    </div>
  </div>
</div>
<%#! @past_events and @upcoming events passed from UserController/show method  %>
<div class="row">
  <div class="col-md-6 col-12 mb-4">
    <%= render partial: "users/attended_events", locals: { events: @past_events } %>
  </div>
  <div class="col-md-6 col-12 mb-4">
    <%= render partial: "users/upcoming_events", locals: { events: @upcoming_events } %>
  </div>
</div>